export PYTHON_BIN_PATH=/usr/bin/python3
export TF_NEED_CUDA=1
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export GCC_HOST_COMPILER_PATH=$(which gcc)
export CUDA_TOOLKIT_PATH=/usr/local/cuda
export TF_CUDA_VERSION=8.0
export CUDNN_INSTALL_PATH=/usr/local/cuda
export TF_CUDNN_VERSION=5
export TF_CUDA_COMPUTE_CAPABILITIES="3.5,5.2"
